(() => {
 'use strict';
 window.createTripPlanner=bridge=>{
  const C=TripCore,D=window.TRAVEL_DATA,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error();},setItem(){throw Error();}};}
  const store=C.createStore(storage),palette=['#1769ba','#b45309','#7c3aed','#047857','#be185d','#0369a1'];
  let shared=null,dayId=store.state.activeDayId,mapDay=false,pick=null,dragged=null,detailReturn='map',daySelections=Object.create(null),busyShare=false;
  let lastGood=C.clone(store.state),toastTimer;
  const current=()=>shared||store.active(),readOnly=()=>Boolean(shared);
  const place=r=>C.resolvePlace(current(),r,D.points)||{name:`资料已不可用（${r.id}）`,address:'',note:'原地点引用保留，可导出或移除。',coordinates:null,_missing:true};
  const refHtml=r=>esc(JSON.stringify(r));
  const parseRef=text=>JSON.parse(text);
  const btn=(action,label,extra='',disabled=false)=>`<button type="button" data-plan-action="${action}" ${extra} ${disabled?'disabled':''}>${label}</button>`;
  function toast(text){clearTimeout(toastTimer);$('planner-toast').textContent=text;$('planner-toast').hidden=false;toastTimer=setTimeout(()=>$('planner-toast').hidden=true,7000);}
  function saved(){ $('save-state').textContent=readOnly()?'分享快照 · 只读':store.message;$('save-state').classList.toggle('save-warning',!readOnly()&&!store.message.includes('已')); }
  function checked(){const t=current();if(t)C.validateTrip(t);}
  function changed(){try{checked();}catch(err){Object.assign(store.state,C.clone(lastGood));render();bridge.refreshCatalogue();$('planner-dialog').close();toast(err.message);throw err;}if(!readOnly()){store.state.activeDayId=dayId;store.save();}lastGood=C.clone(store.state);render();bridge.refreshCatalogue();refreshDetailActions();}
  function day(){return current()?.days.find(d=>d.id===dayId)||null;}
  function dayText(t,index){if(!t.startDate)return `第${index+1}天`;const d=new Date(t.startDate+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+index);return `第${index+1}天 · ${d.toISOString().slice(5,10).replace('-','/')}`;}
  function ensureTrip(){if(current())return true;tripDialog();toast('先为这次旅行创建一份计划，再加入地点。');return false;}
  function dialog(title,body,submitLabel,onSubmit){
   const d=$('planner-dialog');d.innerHTML=`<form id="planner-form"><header><h2>${esc(title)}</h2><button type="button" id="close-planner-dialog" aria-label="关闭窗口">×</button></header><div class="dialog-fields">${body}<p id="dialog-status" role="status"></p></div><footer><button type="button" id="cancel-planner-dialog">取消</button>${submitLabel?`<button class="primary" type="submit">${esc(submitLabel)}</button>`:''}</footer></form>`;
   $('close-planner-dialog').onclick=$('cancel-planner-dialog').onclick=()=>d.close();
   $('planner-form').onsubmit=e=>{e.preventDefault();try{onSubmit?.(new FormData(e.target));}catch(err){$('dialog-status').textContent=err.message||'操作未完成，请检查填写内容。';}};
   d.showModal();d.querySelector('input,select,textarea,button')?.focus();
  }
  function tripDialog(edit=false){cancelPick();const t=edit?current():null;dialog(edit?'修改计划':'新建旅行计划',`<label>计划名称<input name="name" maxlength="100" required value="${esc(t?.name||'我的重庆旅行')}"></label><label>出发日期（可选）<input name="startDate" type="date" value="${esc(t?.startDate||'')}"></label>`,edit?'保存修改':'创建计划',fd=>{const name=String(fd.get('name')).trim();if(!name)throw Error('请填写计划名称。');if(t){t.name=name;t.startDate=String(fd.get('startDate'));}else{const next=C.newTrip(name);next.startDate=String(fd.get('startDate'));store.add(next);shared=null;history.replaceState(null,'',location.pathname+location.search);dayId=next.days[0].id;}changed();$('planner-dialog').close();bridge.showView('plan');});}
  function confirmAction(title,text,action){dialog(title,`<p>${esc(text)}</p>`,title,()=>{action();$('planner-dialog').close();});}
  function addDialog(r){if(readOnly()||!ensureTrip())return;const t=current(),p=place(r);dialog(`加入行程 · ${p.name}`,`<label>安排到<select name="day" aria-label="行程日期">${t.days.map((d,i)=>`<option value="${esc(d.id)}" ${d.id===dayId?'selected':''}>${esc(dayText(t,i))}</option>`).join('')}<option value="unassigned">暂不安排日期</option></select></label><p>同一地点可以重复安排，例如酒店出发与返回。</p>`,'加入行程',fd=>{const destination=String(fd.get('day'));const list=destination==='unassigned'?t.unassigned:t.days.find(d=>d.id===destination)?.stops;if(!list)throw Error('日期已不存在，请重新选择。');if(t.unassigned.length+t.days.reduce((n,d)=>n+d.stops.length,0)>=1000)throw Error('每份计划最多支持1,000项安排。');list.push(C.newStop(r));if(!t.favorites.some(f=>C.refKey(f)===C.refKey(r)))t.favorites.push(C.clone(r));if(destination!=='unassigned')dayId=destination;changed();$('planner-dialog').close();bridge.showView('plan');toast(`已将${p.name}加入行程。`);});}
  function favorite(r){if(readOnly()||!ensureTrip())return;const t=current(),index=t.favorites.findIndex(f=>C.refKey(f)===C.refKey(r));if(index>=0)t.favorites.splice(index,1);else {if(t.favorites.length>=1000)throw Error('想去清单最多支持1,000个地点。');t.favorites.push(C.clone(r));}changed();}
  function lookupStop(id){const t=current();for(const d of t.days){const index=d.stops.findIndex(s=>s.id===id);if(index>=0)return {stop:d.stops[index],list:d.stops,index,day:d};}const index=t.unassigned.findIndex(s=>s.id===id);return index<0?null:{stop:t.unassigned[index],list:t.unassigned,index,day:null};}
  function stopDialog(id){const found=lookupStop(id);if(!found||readOnly())return;const s=found.stop,t=current();dialog(`安排 · ${place(s.place).name}`,`<label>日期<select name="day" aria-label="行程日期">${t.days.map((d,i)=>`<option value="${esc(d.id)}" ${d.id===found.day?.id?'selected':''}>${esc(dayText(t,i))}</option>`).join('')}<option value="unassigned" ${!found.day?'selected':''}>未安排</option></select></label><div class="form-pair"><label>计划到达<input type="time" name="time" value="${esc(s.time)}"></label><label>停留分钟<input type="number" name="duration" min="0" max="1440" step="1" value="${s.duration??''}"></label></div><label>备注<textarea name="note" maxlength="2000" rows="4">${esc(s.note)}</textarea></label>`,'保存安排',fd=>{const target=String(fd.get('day'));s.time=String(fd.get('time'));s.duration=fd.get('duration')===''?null:Number(fd.get('duration'));s.note=String(fd.get('note'));if(target!==(found.day?.id||'unassigned')){const destination=target==='unassigned'?t.unassigned:t.days.find(d=>d.id===target)?.stops;if(!destination)throw Error('日期已不存在。');found.list.splice(found.index,1);destination.push(s);if(target!=='unassigned')dayId=target;}changed();$('planner-dialog').close();});}
  function customDialog(existing=null){if(readOnly()||!ensureTrip())return;const t=current(),p=existing;dialog(p?'编辑手动地点':'添加酒店或其他地点',`<label>地点名称<input name="name" maxlength="100" required value="${esc(p?.name||'')}"></label><label>类别<select name="category">${['酒店','景点','美食','交通','其他'].map(k=>`<option ${p?.category===k?'selected':''}>${k}</option>`).join('')}</select></label><label>地址<input name="address" maxlength="500" value="${esc(p?.address||'')}"></label><label>备注<textarea name="note" maxlength="2000" rows="3">${esc(p?.note||'')}</textarea></label><p>保存后可在地图上标位置；只填名称和地址也能加入行程。</p>`,'保存地点',fd=>{const name=String(fd.get('name')).trim();if(!name)throw Error('请填写地点名称。');if(p){Object.assign(p,{name,category:String(fd.get('category')),address:String(fd.get('address')),note:String(fd.get('note'))});}else{if(t.customPlaces.length>=300)throw Error('每份计划最多支持300个手动地点。');const custom={id:C.uid(),name,category:String(fd.get('category')),address:String(fd.get('address')),note:String(fd.get('note')),coordinates:null};t.customPlaces.push(custom);t.favorites.push({kind:'custom',id:custom.id});}changed();$('planner-dialog').close();bridge.showView('favorites');});}
  function customDetail(r){const p=place(r);bridge.openCustom(p,()=>detailActions(r));}
  function showPlace(r){detailReturn=bridge.getView();if(r.kind==='catalogue'&&D.points.some(p=>p.id===r.id))bridge.openCatalogue(r.id);else customDetail(r);}
  function detailActions(r){const p=place(r),fav=current()?.favorites.some(f=>C.refKey(f)===C.refKey(r));return `<div class="detail-planning" data-detail-ref="${refHtml(r)}">${!readOnly()?btn('favorite',fav?'移出想去':'加入想去',`data-ref="${refHtml(r)}"`)+btn('add-stop','加入行程',`data-ref="${refHtml(r)}"`):''}${navigationHtml(p)}${r.kind==='custom'&&!readOnly()?btn('edit-custom','编辑地点',`data-id="${esc(r.id)}"`)+btn('pick','地图标位置',`data-id="${esc(r.id)}"`)+btn('clear-coordinate','清除标点',`data-id="${esc(r.id)}"`,!p.coordinates):''}</div>`;}
  function navigationHtml(p){return p.coordinates?`<div class="navigation-actions"><select aria-label="导航出行方式"><option value="car">驾车</option><option value="walk">步行</option><option value="bus">公交</option></select><a class="nav-link" href="${esc(C.navigation(p))}" target="_blank" rel="noopener noreferrer" data-nav-ref="${esc(JSON.stringify({name:p.name,coordinates:p.coordinates}))}">高德导航 ↗</a></div>`:btn('copy-address','复制名称与地址',`data-address="${esc([p.name,p.address].filter(Boolean).join(' · '))}"`);}
  function refreshDetailActions(){const old=document.querySelector('#detail-content .detail-planning');if(old){const r=parseRef(old.dataset.detailRef);old.outerHTML=detailActions(r);}}
  function decorateCatalogue(){document.querySelectorAll('#point-list .catalogue-actions').forEach(el=>el.remove());if(readOnly())return;document.querySelectorAll('#point-list [data-point]').forEach(el=>{const r={kind:'catalogue',id:el.dataset.point},fav=current()?.favorites.some(f=>C.refKey(f)===C.refKey(r));el.insertAdjacentHTML('afterend',`<div class="catalogue-actions">${btn('favorite',fav?'已想去 ✓':'＋ 想去',`data-ref="${refHtml(r)}"`)}${btn('add-stop','加入行程',`data-ref="${refHtml(r)}"`)}</div>`);});}
  function render(){
   const t=current();if(t&&!t.days.some(d=>d.id===dayId))dayId=daySelections[t.id]||t.days[0].id;if(t&&!t.days.some(d=>d.id===dayId))dayId=t.days[0].id;
   const options=store.state.trips.map(p=>`<option value="${esc(p.id)}" ${p.id===t?.id&&!readOnly()?'selected':''}>${esc(p.name)}</option>`).join('');
   $('plan-manager').innerHTML=`${readOnly()?'<span class="shared-label">家人分享的行程</span>':`<select id="trip-select" aria-label="切换旅行计划">${options||'<option value="">尚未创建计划</option>'}</select>`}${btn('new-trip','＋ 新计划')}${btn('open-plan','我的行程')}`;
   if($('trip-select'))$('trip-select').onchange=e=>{cancelPick();store.select(e.target.value);mapDay=false;dayId=daySelections[current()?.id]||null;render();bridge.refreshCatalogue();};
   $('planner-panel').innerHTML=!t?`<div class="planner-empty"><div class="planner-eyebrow">把想去的地方安排成一天</div><h2>开始一趟重庆旅行</h2><p>选景点、添酒店，按天安排。计划自动保存在这个浏览器里。</p>${btn('new-trip','创建我的旅行计划','class="primary"')}${btn('import','导入行程备份')}<p class="small-muted">已有地点资料和截图可以直接使用。家人通过分享链接查看你的安排。</p></div>`:`<div class="planner-heading"><span class="planner-eyebrow">${readOnly()?'分享时的快照 · 可以保存副本':'旅行计划'}</span><h2>${esc(t.name)}</h2><p class="small-muted">${t.startDate?'出发 '+esc(t.startDate):'日期可稍后填写'} · ${t.days.length}天 · ${t.days.reduce((n,d)=>n+d.stops.length,0)}项安排</p><div class="plan-toolbar">${readOnly()?btn('save-copy','保存为我的副本','class="primary"')+btn('exit-shared','返回我的计划'):btn('edit-trip','名称 / 日期')+btn('duplicate','复制')+btn('share','分享给家人')+btn('export','导出')+btn('import','导入')+btn('delete-trip','删除')}</div></div><div class="day-tabs" aria-label="行程日期">${t.days.map((d,i)=>btn('select-day',esc(dayText(t,i)),`data-id="${esc(d.id)}" aria-pressed="${d.id===dayId}" style="--day-color:${palette[i%palette.length]}"`)).join('')}${!readOnly()?btn('add-day','＋ 天数','',t.days.length>=60):''}</div><div class="day-toolbar">${btn('fit-day','查看全天范围')}${btn('all-points','全部地点')}${!readOnly()?btn('delete-day','删除这一天','',t.days.length===1):''}</div><p class="route-explanation">顺序示意，非实际交通路线。时间由你填写，交通耗时请查看导航。</p><div class="stop-list">${day()?.stops.length?day().stops.map((s,i)=>stopHtml(s,i,day().stops.length)).join(''):'<div class="planner-day-empty"><h3>这一天还没有安排</h3><p>从“找地点”或“想去”加入地点，再调整游览顺序。</p>'+(!readOnly()?btn('find-places','去选地点'):'')+'</div>'}</div>${!readOnly()?`<div class="day-footer">${btn('find-places','＋ 从地点库添加')}${btn('custom','＋ 酒店 / 其他地点')}</div>`:''}<details class="unassigned"><summary>未安排日期 · ${t.unassigned.length}项</summary>${t.unassigned.map((s,i)=>stopHtml(s,i,t.unassigned.length)).join('')||'<p>删除日期后的安排会保留在这里。</p>'}</details>`;
   $('favorites-panel').innerHTML=`<div class="favorites-heading"><div class="library-tabs">${btn('find-places','找地点')}${btn('open-favorites','想去','aria-pressed="true"')}</div><h2>想去的地方</h2><p>${t?esc(t.name):'先创建一份计划，再收藏想去的地方。'}</p>${!readOnly()?btn('custom','＋ 添加酒店 / 其他地点'):''}</div>${t?.favorites.length?t.favorites.map(r=>{const p=place(r);return `<article class="favorite-card">${btn('open-place',esc(p.name),`class="favorite-name" data-ref="${refHtml(r)}"`)}<p>${r.kind==='custom'?'手动添加 · '+esc(p.category||'其他'):esc(p.region||'原地点资料')} · ${p.coordinates?'已标位置':'未标位置'}</p>${p.address?`<p>${esc(p.address)}</p>`:''}${!readOnly()?`<div class="card-actions">${btn('add-stop','加入行程',`data-ref="${refHtml(r)}"`)}${btn('favorite','移出想去',`data-ref="${refHtml(r)}"`)}${r.kind==='custom'?btn('pick','地图标位置',`data-id="${esc(r.id)}"`):''}</div>`:''}</article>`;}).join(''):'<div class="empty-favorites">看中一个地点，点击“加入想去”。酒店和其他地点也可以手动添加。</div>'}`;
   bridge.setCustomPlaces(t?.customPlaces||[],p=>showPlace({kind:'custom',id:p.id}));saved();renderMap();if(!readOnly())lastGood=C.clone(store.state);
  }
  function stopHtml(s,i,count){const p=place(s.place);return `<article class="stop-card" draggable="${!readOnly()}" data-stop="${esc(s.id)}"><div class="stop-title">${!readOnly()?'<span class="drag-handle" title="拖动调整顺序" aria-hidden="true">⠿</span>':''}<span class="stop-number">${i+1}</span>${btn('open-place',esc(p.name),`data-ref="${refHtml(s.place)}"`)}${!p.coordinates?'<span class="missing-position">未标位置</span>':''}</div><p class="stop-time">${s.time?esc(s.time):'时间未填写'}${s.duration!==null?' · 停留'+s.duration+'分钟':''}</p>${s.note?`<p class="stop-note">${esc(s.note)}</p>`:''}${s.place.kind==='custom'?'<p class="small-muted">手动添加地点</p>':''}<div class="card-actions">${!readOnly()?btn('edit-stop','时间 / 备注 / 日期',`data-id="${esc(s.id)}"`)+btn('up','上移',`data-id="${esc(s.id)}" aria-label="上移 ${esc(p.name)}"`,i===0)+btn('down','下移',`data-id="${esc(s.id)}" aria-label="下移 ${esc(p.name)}"`,i===count-1)+btn('remove-stop','移除',`data-id="${esc(s.id)}"`):''}${navigationHtml(p)}</div></article>`;}
  function renderMap(fit=false){const t=current(),d=day();if(!mapDay||!t||!d){bridge.setDayMap(null);return;}const route=C.segments(d.stops,place),color=palette[t.days.indexOf(d)%palette.length];bridge.setDayMap({...route,color,label:dayText(t,t.days.indexOf(d))},r=>showPlace(r));if(fit){bridge.cancelCentering();if(route.markers.length)bridge.fitCoordinates(route.markers.map(m=>m.coordinates));else toast('这一天还没有已标位置的地点，仍可查看行程列表。');}}
  function reorder(id,delta){const found=lookupStop(id);if(!found)return;const next=found.index+delta;if(next<0||next>=found.list.length)return;[found.list[found.index],found.list[next]]=[found.list[next],found.list[found.index]];changed();$('planner-panel').querySelector(`[data-stop="${id}"] [data-plan-action="${delta<0?'up':'down'}"]`)?.focus();}
  async function copy(text){try{await navigator.clipboard.writeText(text);toast('已复制。');return true;}catch{dialog('手动复制',`<label>长按或选中以下内容复制<textarea readonly rows="6">${esc(text)}</textarea></label>`,null);return false;}}
  function download(){const t=current();if(!t)return;const blob=new Blob([C.fileText(t)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(t.name.replace(/[\\/:*?"<>|]/g,'_')||'旅行计划')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出行程文件，可传到另一台设备后导入。');}
  function shareDialog(){const t=current();if(!t)return;const link='https://key-kun.github.io/chongqing-travel-map/#trip='+encodeURIComponent(LZString.compressToEncodedURIComponent(C.fileText(t)));const long=link.length>8000;dialog('分享给家人',`<p>分享包含这份计划的地点、日期安排和备注。家人看到的是现在的快照；后续修改需要重新分享。</p><p>链接中的行程可被收到链接的人查看，当前位置不会加入分享。</p>${long?'<p>这份计划内容较多，链接超过8,000字符，请导出行程文件分享。</p>':`<label>分享链接<textarea id="share-link" rows="5" readonly>${esc(link)}</textarea></label>`}`,long?'导出行程文件':'复制分享链接',async()=>{if(long){download();$('planner-dialog').close();return;}try{await navigator.clipboard.writeText(link);$('dialog-status').textContent='已复制，发送给家人即可查看。';}catch{$('dialog-status').textContent='未能自动复制，请长按或选中上面的链接手动复制。';$('share-link').focus();$('share-link').select();}});}
  function startPick(id){const p=current()?.customPlaces.find(p=>p.id===id);if(!p)return;pick={id,coordinates:null};bridge.closeDetail();bridge.showView('map');$('pick-panel').hidden=false;$('pick-text').textContent=`为“${p.name}”标位置：点击地图，再确认。`;$('confirm-pick').disabled=true;bridge.startPick(c=>{pick.coordinates=c;$('pick-text').textContent=`已选 ${c.lat.toFixed(6)}, ${c.lng.toFixed(6)}，请核对后确认。`;$('confirm-pick').disabled=false;});}
  function cancelPick(){pick=null;bridge.endPick();$('pick-panel').hidden=true;}
  $('cancel-pick').onclick=cancelPick;$('confirm-pick').onclick=()=>{if(!pick?.coordinates)return;const p=current()?.customPlaces.find(p=>p.id===pick.id);if(!p){cancelPick();return;}p.coordinates=pick.coordinates;cancelPick();changed();bridge.showView('favorites');toast('手动地点已标位置。');};
  const actions={
   'new-trip':()=>tripDialog(),'open-plan':()=>bridge.showView('plan'),'edit-trip':()=>tripDialog(true),
   duplicate:()=>{const t=C.duplicateTrip(current());t.name=(t.name+' · 副本').slice(0,100);store.add(t);dayId=null;mapDay=false;changed();},
   'delete-trip':()=>confirmAction('删除计划','删除后只能从导出的备份恢复。其他计划不会受影响。',()=>{store.remove(current().id);dayId=null;mapDay=false;render();bridge.refreshCatalogue();}),
   'add-day':()=>{const t=current();if(t.days.length>=60)return;const d={id:C.uid(),stops:[]};t.days.push(d);dayId=d.id;changed();},
   'delete-day':()=>{const t=current();if(t.days.length<=1)return;confirmAction('删除这一天','这一天的地点和备注会转入“未安排日期”。',()=>{const d=day();t.unassigned.push(...d.stops);t.days=t.days.filter(x=>x.id!==d.id);dayId=t.days[0].id;changed();});},
   'select-day':b=>{dayId=b.dataset.id;daySelections[current().id]=dayId;if(!readOnly()){store.state.activeDayId=dayId;store.save();}mapDay=true;render();},
   'fit-day':()=>{mapDay=true;renderMap(true);bridge.showView('map');},'all-points':()=>{mapDay=false;renderMap();bridge.showView('map');},
   'find-places':()=>bridge.showView('list'),'open-favorites':()=>bridge.showView('favorites'),custom:()=>customDialog(),favorite:b=>favorite(parseRef(b.dataset.ref)),
   'add-stop':b=>addDialog(parseRef(b.dataset.ref)),'open-place':b=>showPlace(parseRef(b.dataset.ref)),
   'edit-stop':b=>stopDialog(b.dataset.id),'edit-custom':b=>customDialog(current().customPlaces.find(p=>p.id===b.dataset.id)),
   up:b=>reorder(b.dataset.id,-1),down:b=>reorder(b.dataset.id,1),'remove-stop':b=>{const f=lookupStop(b.dataset.id);if(f){f.list.splice(f.index,1);changed();}},
   pick:b=>startPick(b.dataset.id),'clear-coordinate':b=>{current().customPlaces.find(p=>p.id===b.dataset.id).coordinates=null;changed();},
   'copy-address':b=>copy(b.dataset.address),export:download,share:shareDialog,import:()=>$('import-trip').click(),
   'save-copy':()=>{const next=C.duplicateTrip(shared);next.name=(next.name+' · 我的副本').slice(0,100);store.add(next);shared=null;history.replaceState(null,'',location.pathname+location.search);dayId=null;mapDay=false;changed();toast('已保存为独立副本，家人的原分享不会改变。');},
   'exit-shared':()=>{shared=null;dayId=null;mapDay=false;history.replaceState(null,'',location.pathname+location.search);render();bridge.refreshCatalogue();}
  };
  const readonlyAllowed=new Set(['new-trip','open-plan','select-day','fit-day','all-points','open-place','copy-address','export','save-copy','exit-shared']);
  document.addEventListener('click',e=>{const b=e.target.closest('[data-plan-action]');if(!b||b.disabled)return;const action=b.dataset.planAction;if(readOnly()&&!readonlyAllowed.has(action))return;try{actions[action]?.(b);}catch(err){toast(err.message||'操作未完成，请导出当前计划备份。');}});
  document.addEventListener('change',e=>{if(e.target.matches('.navigation-actions select')){const a=e.target.parentElement.querySelector('a');a.href=C.navigation(JSON.parse(a.dataset.navRef),e.target.value);}});
  $('planner-panel').addEventListener('dragstart',e=>{if(readOnly())return;const card=e.target.closest('[data-stop]');if(!card||e.target.closest('button,a,select,input')){e.preventDefault();return;}dragged=card.dataset.stop;e.dataTransfer.setData('text/plain',dragged);e.dataTransfer.effectAllowed='move';});
  $('planner-panel').addEventListener('dragover',e=>{if(dragged&&e.target.closest('[data-stop]'))e.preventDefault();});
  $('planner-panel').addEventListener('drop',e=>{e.preventDefault();const id=e.target.closest('[data-stop]')?.dataset.stop;if(!dragged||!id)return;const from=lookupStop(dragged),to=lookupStop(id);dragged=null;if(!from||!to||from.list!==to.list)return;from.list.splice(from.index,1);from.list.splice(to.index,0,from.stop);changed();});
  $('planner-panel').addEventListener('dragend',()=>{dragged=null;});
  $('import-trip').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>C.MAX_BYTES)throw Error('行程文件超过500KB。');const t=C.duplicateTrip(C.parseFile(await f.text()));cancelPick();store.add(t);shared=null;history.replaceState(null,'',location.pathname+location.search);dayId=null;mapDay=false;changed();bridge.showView('plan');toast('已导入为新计划，原有计划保留。');}catch(err){toast(err.message||'无法读取行程文件。');}};
  function decodeShared(encoded){return new Promise((resolve,reject)=>{if(encoded.length>24000){reject(Error('分享链接过长，请让家人改用行程文件分享。'));return;}let worker,timer;try{worker=new Worker('trip-share-worker.js');timer=setTimeout(()=>{worker.terminate();reject(Error('分享链接无法解析，请让家人重新分享。'));},2000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();if(e.data.error)reject(Error('分享链接已损坏，请让家人重新分享。'));else try{resolve(C.parseFile(e.data.text));}catch(err){reject(err);}};worker.onerror=()=>{clearTimeout(timer);worker.terminate();reject(Error('分享组件暂时无法加载，请刷新后重试。'));};worker.postMessage(decodeURIComponent(encoded));}catch{clearTimeout(timer);worker?.terminate();reject(Error('分享链接已损坏，请让家人重新分享。'));}});}
  async function loadShared(){if(!location.hash.startsWith('#trip='))return;busyShare=true;toast('正在打开家人分享的行程…');try{shared=await decodeShared(location.hash.slice(6));dayId=shared.days[0].id;mapDay=true;render();bridge.refreshCatalogue();bridge.showView('plan');toast('已打开只读快照，可以保存为自己的副本。');}catch(err){toast(err.message);}finally{busyShare=false;}}
  window.addEventListener('hashchange',()=>{if(!busyShare)loadShared();});
  render();decorateCatalogue();loadShared();
  return {decorateCatalogue,detailActions,readOnly,returnView:()=>detailReturn,current,clearDayMap(){mapDay=false;renderMap();},setDetailReturn(view){detailReturn=view;},onView(view){if(pick&&view!=='map')cancelPick();}};
 };
})();
